version: "3.1"
services: 
  db:
    image: mongo:latest
    container_name: db
    env_file: 
      - docker.env
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - './seed.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'


  api: 
    image: node:latest
    container_name: api
    restart: always
    env_file: 
      - docker.env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules/
    working_dir: /usr/src/api
    command: sh -c "npm install && npm run start" 
    links: 
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"